name: UpdateDependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Setup DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.112'
    - 
      name: Install dependencies
      run: |
        cd server/
        dotnet restore
    - 
      name: Update using NuGet
      uses: Bchir/update-nuget@V1.0.0
      with:
        searchFor: 'outdated'
        versionToSelect: 'highest-minor'
        directory: ./server
