name: UpdateDependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Setup DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.112'
    - 
      name: Update packages
      uses: stphnwlsh/dotnet-outdated-action@v2
      with:
        location: ./server
    -
      name: Commit the changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.name 'GitHub Action'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -am "Updated dependencies"
          git push
        else
          echo "No changes, skipping."
        fi
